### ISSUE TITLE
GitHub Authentication

### ISSUE THREAD

**Issue by zimt28** [CyCoreSystems/docker-meteor#14] opened 2016-03-14 20:58 UTC
Hey, it would be nice if you could tell me what I'm doing wrong here.
My app's code is hosted on GitHub, so I want to pull from there.

To test how this image works I've created a fresh DO instance, ran `ssh-keygen` and added the public key to the repo as a deploy key. Now, when I want to run the app, I get an error:

``` sh
docker run --rm \
  -e ROOT_URL=http://testsite.com \
  -e METEOR_SETTINGS='{"some": "settings"}' \
  -e REPO=https://github.com/zimt28/app \
  -e DEPLOY_KEY=/key \
  -v /root/.ssh/id_rsa.pub:/key \
  -e MONGO_URL=mongodb://url \
  ulexus/meteor
```

``` sh
Cloning https://github.com/zimt28/app...
Cloning into '/src/app'...
fatal: could not read Username for 'https://github.com': No such device or address
```

And idea what's wrong with my approach? Thanks!

**Comment by Ulexus** [comment] 2016-03-14 21:20
Two things that I see straight off:
 - If you want to use the SSH key, you need to use the ssh protocol in the REPO url; refer your the Github repo to get the correct SSH clone URL.
 - The SSH client needs the _private_ key, not the public key

**Comment by zimt28** [comment] 2016-03-14 22:06
Hi @Ulexus, thanks for your response! Authentication works, now I get this error:

```
Building the bundle...(this may take a while)
/usr/bin/entrypoint.sh: line 107:    45 Killed                  meteor build --directory ${APP_DIR}
Building the bundle (old version)...
This command has been deprecated in favor of 'meteor build', which allows you
to build for multiple platforms and outputs a directory instead of a single
tarball. See 'meteor help build' for more information.
```
And after that: https://gist.github.com/zimt28/6b60bdb597efdc3164e3

**Comment by Ulexus** [comment] 2016-03-15 02:13
It looks like you've got a problem installing your npm dependencies.  Are you using any interesting modules?  Perhaps some local ones with odd or non-published npm dependencies?

If `meteor build` fails, the script attempts to fall back to the old pre-0.9 `meteor bundle` method.  That's a red herring in your case.  The problem is in the gist:  the npm dependency resolution is failing.

**Comment by zimt28** [comment] 2016-03-15 07:55
@Ulexus Nothing that I'm aware of. I'm currently using `meteord` to dockerize my application, but building the image takes about 10 minutes, so I'm looking for an alternative. However, `meteord` also builds the application, but without problems.

**Comment by codeHatcher** [comment] 2016-09-22 17:08
Seems I'm also having a similar issue @zimt28 how did you end up solving this?

**Comment by Ulexus** [comment] 2016-09-22 23:55
@codeHatcher Could you supply a bit more information?  How are you supplying the keyfile to the container?  How are you referencing it with `DEPLOY_KEY`?

**Comment by codeHatcher** [comment] 2016-09-23 00:00
I don't think I am seeing any auth issues. I created a new key pair added the public key to github and then linked the private key using that -v flag

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.0.74&pv=9.3.5&source=email_footer_2]
On Thu, Sep 22, 2016 at 4:55 PM, Seán C. McCord <notifications@github.com> wrote:
@codeHatcher [https://github.com/codeHatcher] Could you supply a bit more information? How are you supplying the keyfile to the container? How are you referencing it with DEPLOY_KEY ?

**Comment by codeHatcher** [comment] 2016-09-23 00:01
The reason I don't think I am having an auth issue is because I was previously having auth issues which were made clear to me via a different error which I then resolved with the -v flag

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.0.74&pv=9.3.5&source=email_footer_2]
On Thu, Sep 22, 2016 at 4:55 PM, Seán C. McCord <notifications@github.com> wrote:
@codeHatcher [https://github.com/codeHatcher] Could you supply a bit more information? How are you supplying the keyfile to the container? How are you referencing it with DEPLOY_KEY ?

**Comment by Ulexus** [comment] 2016-09-23 00:10
@codeHatcher I'm confused, then.  Why did you say you are having the same problem?

**Comment by codeHatcher** [comment] 2016-09-23 00:40
I'm having his most recent problem, not his auth problem. The one that says

> @Ulexus Nothing that I'm aware of. I'm currently using meteord to dockerize my application, but building the image takes about 10 minutes, so I'm looking for an alternative. However, meteord also builds the application, but without problems.

> Edit: local meteor build --architecture=os.linux.x86_64 ./build works fine, too.

That's why I was saying I'm having the same problem

**Comment by Ulexus** [comment] 2017-01-22 22:42
Closing old issue; feel free to reopen if this is not resolved.

**Closed by Ulexus** 2017-01-22 22:42 UTC
