### ISSUE TITLE
Blocked in step 'Starting Meteor Application ...' 

### ISSUE THREAD

**Issue by Brouilles** [CyCoreSystems/docker-meteor#50] opened 2017-07-27 16:53 UTC
Hello,
I have a problem with docker-meteor, i'm use Docker on Windows 10 and the container stand at this step ' Starting Meteor Application ...'. Without change several minutes. I have build the project with 'meteor build ../' on Windows. And use this docker-compose (same problem directly with the docker command): https://pastebin.com/VfjKxAPi

![Image](https://img4.hostingpics.net/pics/777145Docker.png)

Thanks for your awnser.

**Comment by abate** [comment] 2017-10-04 15:34
I had a similar problem caused by the fact that my node_modules where missing. Running 

meteor npm install

in my app directory solved this problem.

I'm wondering if this command should be run in the entrypoint.sh script as well. In particular if the repository if fetched via git and the node_modules are not committed.

**Comment by Ulexus** [comment] 2017-10-06 15:16
@abate That's a good question.  `npm install` is run in the server-internal directory, but now that npm is used everywhere in Meteor, that may well need to be done.  At a minimum, it probably shouldn't be disruptive.

**Comment by Ulexus** [comment] 2017-10-06 15:18
@abate Never mind, we're doing that already, [here](https://github.com/CyCoreSystems/docker-meteor/blob/4f786b078b84f23d81d924272f18db3a72702db7/entrypoint.sh#L110).

**Comment by abate** [comment] 2017-10-06 15:26
not sure that **npm install**  is the same as calling **meteor npm install** . For once, it will use the npm version bundled in meteor ... I'm not entirely sure, but I've noticed in my project that npm install is not enough to install all the modules in node_modules directory ...

**Comment by Ulexus** [comment] 2017-10-06 15:39
@abate Yeah, I'll change that to `meteor npm install`, which should be safer.

**Comment by Ulexus** [comment] 2017-10-06 15:44
Fixed by a8acdd5efe5af2ff70450e4667920f671093011d

**Closed by Ulexus** 2017-10-06 15:44 UTC

**Comment by yusef-ho** [comment] 2018-03-05 06:48
Hello, thanks for your work.
But i'm facing the same problem event i updated to latest version of image

![image](https://user-images.githubusercontent.com/33569998/36960968-36742b50-2084-11e8-99da-62fdedbd2ce3.png)

**Comment by Ulexus** [comment] 2018-03-05 16:56
I don't see any errors in that screenshot, but did you see any in the backscroll?  Anyway, how do you know it isn't working?  Have you expose the port you expect it to be running on?  Would you care to post your invocation commandline for verification?
